# Generated by Django 5.1.7 on 2025-05-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_title', models.CharField(max_length=255)),
                ('en_short_description', models.TextField(max_length=1000)),
                ('en_banner_image', models.ImageField(upload_to='banner/')),
                ('ch_title', models.CharField(max_length=255)),
                ('ch_short_description', models.TextField(max_length=1000)),
                ('ch_banner_image', models.ImageField(upload_to='banner/')),
            ],
            options={
                'verbose_name': '03. About Section',
                'verbose_name_plural': '03. About Section',
            },
        ),
        migrations.CreateModel(
            name='AllServicesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_title', models.CharField(max_length=255)),
                ('en_short_description', models.TextField(max_length=500)),
                ('ch_title', models.CharField(max_length=255)),
                ('ch_short_description', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': '08. All Services Section',
                'verbose_name_plural': '08. All Services Section',
            },
        ),
        migrations.CreateModel(
            name='ApproachSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_title', models.CharField(max_length=255)),
                ('en_description', models.TextField(max_length=1000)),
                ('ch_title', models.CharField(max_length=255)),
                ('ch_description', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name': '06. Our Approach Section',
                'verbose_name_plural': '06. Our Approach Section',
            },
        ),
        migrations.CreateModel(
            name='CommitmentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_title', models.CharField(max_length=255)),
                ('en_short_description', models.TextField(max_length=1000)),
                ('en_banner_image', models.ImageField(upload_to='banner/')),
                ('ch_title', models.CharField(max_length=255)),
                ('ch_short_description', models.TextField(max_length=1000)),
                ('ch_banner_image', models.ImageField(upload_to='banner/')),
            ],
            options={
                'verbose_name': '07. Our Commitment Section',
                'verbose_name_plural': '07. Our Commitment Section',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_address', models.TextField(max_length=1000)),
                ('en_email', models.CharField(max_length=50)),
                ('en_phone', models.CharField(max_length=50)),
                ('ch_address', models.TextField(max_length=1000)),
                ('ch_email', models.CharField(max_length=50)),
                ('ch_phone', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '10. Contact Details',
                'verbose_name_plural': '10. Contact Details',
            },
        ),
        migrations.CreateModel(
            name='CounterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_value', models.CharField(max_length=255)),
                ('en_title', models.CharField(max_length=500)),
                ('ch_value', models.CharField(max_length=255)),
                ('ch_title', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': '05. Counter Section',
                'verbose_name_plural': '05. Counter Section',
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_title', models.CharField(max_length=255)),
                ('en_short_description', models.TextField(max_length=500)),
                ('en_banner_image', models.ImageField(upload_to='banner/')),
                ('ch_title', models.CharField(max_length=255)),
                ('ch_short_description', models.TextField(max_length=500)),
                ('ch_banner_image', models.ImageField(upload_to='banner/')),
            ],
            options={
                'verbose_name': '02. Hero Section',
                'verbose_name_plural': '02. Hero Section',
            },
        ),
        migrations.CreateModel(
            name='PricingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_currency_title', models.CharField(max_length=255)),
                ('en_short_description', models.TextField(max_length=1000)),
                ('ch_currency_title', models.CharField(max_length=255)),
                ('ch_short_description', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name': '13. Pricing Section',
                'verbose_name_plural': '13. Pricing Section',
            },
        ),
        migrations.CreateModel(
            name='ServiceSummarySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_service_summary_title', models.CharField(max_length=255)),
                ('en_short_description', models.TextField(max_length=1000)),
                ('ch_service_summary_title', models.CharField(max_length=255)),
                ('ch_short_description', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name': '04. Service Summary Section',
                'verbose_name_plural': '04. Service Summary Section',
            },
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '11. Social Links',
                'verbose_name_plural': '11. Social Links',
            },
        ),
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon_icon', models.ImageField(blank=True, null=True, upload_to='favicon_icons/')),
                ('website_logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('service_section_background_image', models.ImageField(blank=True, null=True, upload_to='service_background_image/')),
                ('en_website_title', models.CharField(max_length=255)),
                ('en_website_nav_title', models.CharField(blank=True, max_length=255, null=True)),
                ('ch_website_title', models.CharField(max_length=255)),
                ('ch_website_nav_title', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': '12. Website Settings',
                'verbose_name_plural': '12. Website Settings',
            },
        ),
        migrations.CreateModel(
            name='WebsiteTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_about_title', models.CharField(max_length=1000)),
                ('en_about_short_description', models.TextField(max_length=1000)),
                ('en_summary_service_title', models.CharField(max_length=1000)),
                ('en_summary_service_short_discription', models.TextField(max_length=1000)),
                ('en_approach_title', models.CharField(max_length=1000)),
                ('en_approach_short_discription', models.TextField(max_length=1000)),
                ('en_all_service_title', models.CharField(max_length=1000)),
                ('en_all_service_discription', models.TextField(max_length=1000)),
                ('en_packages_title', models.CharField(max_length=1000)),
                ('en_packages_short_description', models.TextField(max_length=1000)),
                ('en_whychooseus_title', models.CharField(max_length=1000)),
                ('en_whychooseus_short_description', models.TextField(max_length=1000)),
                ('en_contact_title', models.CharField(max_length=1000)),
                ('en_contact_short_description', models.TextField(max_length=1000)),
                ('ch_about_title', models.CharField(max_length=1000)),
                ('ch_about_short_description', models.TextField(max_length=1000)),
                ('ch_summary_service_title', models.CharField(max_length=1000)),
                ('ch_summary_service_short_discription', models.TextField(max_length=1000)),
                ('ch_approach_title', models.CharField(max_length=1000)),
                ('ch_approach_short_discription', models.TextField(max_length=1000)),
                ('ch_all_service_title', models.CharField(max_length=1000)),
                ('ch_all_service_discription', models.TextField(max_length=1000)),
                ('ch_packages_title', models.CharField(max_length=1000)),
                ('ch_packages_short_description', models.TextField(max_length=1000)),
                ('ch_whychooseus_title', models.CharField(max_length=1000)),
                ('ch_whychooseus_short_description', models.TextField(max_length=1000)),
                ('ch_contact_title', models.CharField(max_length=1000)),
                ('ch_contact_short_description', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name': '01. Website Section Titles',
                'verbose_name_plural': '01. Website Section Titles',
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_title', models.CharField(max_length=255)),
                ('en_short_description', models.TextField(max_length=500)),
                ('ch_title', models.CharField(max_length=255)),
                ('ch_short_description', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': '09. Why Choose Us',
                'verbose_name_plural': '09. Why Choose Us',
            },
        ),
    ]
