# Generated by Django 5.1.7 on 2025-05-06 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_aboutsection_ch_banner_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsection',
            name='ch_banner_image',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='ch_short_description',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='ch_title',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='en_short_description',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='en_title',
        ),
    ]
