# Generated by Django 5.1.7 on 2025-05-06 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_aboutsection_ch_banner_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herosection',
            name='ch_banner_image',
        ),
    ]
