# Generated by Django 5.1.7 on 2025-05-06 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_herosection_ch_banner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commitmentsection',
            name='ch_banner_image',
        ),
    ]
